### ISSUE TITLE
Trident RC2 - Falkon Qt5 SIGBUS Crash

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-build#10]
I am not sure where this is related to underlying Qt5 library dependency issue with RC2 build and whether the rebuild will fix it. So here is the evidence  of crash to clarify.

Error log when starting up:
> QKqueueFileSystemWatcherEngine::addPaths: open: No such file or directory

Does this look expected that there is mixture of Qt5 5.9 and 5.11?
> -rwxr-xr-x  1 root  wheel    123080 Oct  9 08:50 /usr/local/lib/qt5/libQt5WebChannel.so.5.11.2
> -rwxr-xr-x  1 root  wheel  84201312 Oct  9 14:46 /usr/local/lib/qt5/libQt5WebEngineCore.so.5.9.5
> 

Also please find the full GDB backtrace attached.

[falkon_sigbus_gdb.txt](https://github.com/project-trident/trident-build/files/2494079/falkon_sigbus_gdb.txt)

**Comment by RodMyers** [comment]
Have you tried RC3?

**Comment by RodMyers** [comment]
no response in a fortnight
