### ISSUE TITLE
The install disk does not see my SSD Samsung 850 PRO

### ISSUE THREAD

**Issue by sailorsamoor** [project-trident/trident-build#11]
Hello. Can't install Trident. The system disk see my old maxtor, my Seagate, but does not see SSD. 
I tried to change SATA ports but it is still the same.
P.S. dmesg , which is inTrident, says that my hard system has ada0,ada1,ada2 - all my disks are  ready.

**Comment by RodMyers** [comment]
Have to tried RC3?

**Comment by sailorsamoor** [comment]
Not. I decided to install pure FreeBSD. I will to watch for Trident, but now FreeBSD is better for me. Tank you for your time and your work.

**Comment by RodMyers** [comment]
moved to FreeBSD
