### ISSUE TITLE
KIndly make a separate repo of the GCC/CLang based x64 bare metal compiler?

### ISSUE THREAD

**Issue by EasyTechClick** [project-trident/trident-build#13]
Hi

Can you make a repo out of the compiler (x64 based) which you are  using? Also can you also post instructions for creating the compiler?

Thanks,
Arvind.

**Comment by beanpole135** [comment]
We do not use a custom compiler, nor do we host any version of the compiler(s) that are used during the build process.

Project Trident uses the standard "llvm60" compiler package (clang) from FreeBSD/TrueOS, although some ports do designate that they need/use GCC instead (which will then be installed/used as a build dependency for that port/package). The version of llvm/gcc that is used mey change to newer versions at some time down the road as well, depending on when the default compiler versions are updated in FreeBSD/TrueOS.

Links for additional reading:
LLVM60 port in TrueOS: https://github.com/trueos/trueos-ports/tree/trueos-master/devel/llvm60
GCC8 port in TrueOS (current default for Project Trident): https://github.com/trueos/trueos-ports/tree/trueos-master/lang/gcc8
