### ISSUE TITLE
11/23 Pre-Release build with Witness debugger option enabled

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-build#15]
I can see on boot-up that the latest 11/23 Pre-Release ISO  seems to be built with FreeBSD  kernel debug configuration. I didnt see evidence of the below option being enabled in the kernel log on the prior builds.

The kernel build should probably reference the following configuration for 64-bit architecture: https://github.com/freebsd/freebsd/blob/master/sys/amd64/conf/GENERIC-NODEBUG

> 
> Nov 24 23:41:13  kernel: All buffers synced.
> Nov 24 23:41:13  kernel: lock order reversal:
> Nov 24 23:41:13  kernel:  1st 0xfffff80007686608 isofs (isofs) @ /usr/src_tmp/sys/kern/vfs_mount.c:1347
> Nov 24 23:41:13  kernel:  2nd 0xfffff8000740f248 devfs (devfs) @ /usr/src_tmp/sys/kern/vfs_subr.c:2590
> Nov 24 23:41:13  kernel: Uptime: 38m50s
> Nov 24 23:41:13  kernel: uhub_reattach_port: giving up port reset - device vanished
> Nov 24 23:41:13  kernel: ---<<BOOT>>---
> Nov 24 23:41:13  kernel: Copyright (c) 1992-2018 The FreeBSD Project.
> Nov 24 23:41:13  kernel: Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
> Nov 24 23:41:13  kernel:        The Regents of the University of California. All rights reserved.
> Nov 24 23:41:13  kernel: FreeBSD is a registered trademark of The FreeBSD Foundation.
> Nov 24 23:41:13  kernel: FreeBSD 13.0-CURRENT GENERIC amd64
> Nov 24 23:41:13  kernel: FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
> Nov 24 23:41:13  kernel: WARNING: WITNESS option enabled, expect reduced performance.

**Comment by beanpole135** [comment]
This is already fixed/disabled in later versions.
Closing...
