### ISSUE TITLE
chromium/chrome ld-elf.so.1: /usr/local/lib/libglib-2.0.so.0: Undefined symbol "environ"

### ISSUE THREAD

**Issue by krgrose** [project-trident/trident-build#19]
With a freshly installed vanilla Project Trident OS

OS Version: 18.12-PRERELEASE2
Build Date: 20181219130325

put into a new VirtualBox VM and then adding only one package (chromium), trying to start chrome from the command line fails with the undefined symbol error noted in the issue title. The same symptom happens following an upgrade to PRERELEASE2 from the previous release (18.12 PRERELEASE) where the installed and working chromium is rendered inoperative.

**Comment by beanpole135** [comment]
This took quite a bit of work, but is fixed in the upcoming 18.12-RELEASE.
