### ISSUE TITLE
Possibility to run on USB stick

### ISSUE THREAD

**Issue by Ygarr** [project-trident/trident-build#21]
Please add possibility to use TridentOS on USB stick and save/write changes to it aka persistence. Like [NomadBSD](https://github.com/mrclksr/NomadBSD) but with "toram" function

**Comment by q5sys** [comment]
You can already install Trident to a USB stick and save changes to disk.  The USB stick will be seen just like any other usb disk. 
However, it will not operate as a live image in RAM.  There are severe limitations with unionfs on FreeBSD.  Until features are added, or a new layered file system like AUFS from linux is written for FreeBSD,  running from RAM and saving changes to disk will not be possible for the foreseeable future. 

I looked into this when I came over to do development for TrueOS from Linux.  As I used AUFS, I was highly interested in being able to do this on FreeBSD, alas... the kernel doesn't have the features its needs to make this a reality. 

You can have a persistent USB install that allows changes.  Or you can have a live stateless image that can be loaded into and run from RAM.  You cannot have both.
