### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by bozhikovstanislav** [project-trident/trident-build#28]
When trying to update from 19.05 to 19.06 - it get nonworking system.
sudo useres are out - have to re-enable them.
sysadm service do not work
no restart

**Comment by beanpole135** [comment]
You did not apply the pre-update errata/patch which we published in both the release announcement[1] as well as the graphical update manager (19.05+).
You will need to roll back your boot environment and then apply the patch before proceeding with the update again.

https://project-trident.org/post/2019-06-28_19.06_available/

**Comment by bozhikovstanislav** [comment]
this do not work at all I try it :(

**Comment by maxsteciuk** [comment]
Could you please be more specific? What were the steps you tried and what didn’t work?
The steps should’ve been in this order:
1. Rollback to previous BE, by selecting it via bootmgr (option 7) 
2. Ensure broken BE (U6) is removed; via trident-updatemgr GUI
3. sudo pkg -fy install sysup
4. Check & start upgrade via trident-updatemgr GUI

**Comment by bozhikovstanislav** [comment]
first when trying to install from usb - mouse do not respond at all Ican not continue
second
I perform
sudo pkg -fy install sysup

and again do not work

**Comment by beanpole135** [comment]
From 19.05 Boot environment:
1. Run: `sudo pkg install -fy sysup`
   * This will bootstrap the newer version of the update utility
2. Run: `sudo sysup -update`
   * This will perform the updates (previously downloaded files will be re-used, so this should not take long at all)
3. Run: `shutdown -r now`
   * This will reboot the system to finish applying updates

**Comment by bozhikovstanislav** [comment]
ok Now I am doing this .. will tell you if it get OK

**Comment by bozhikovstanislav** [comment]
sysadm service do not running ..

this is the result

**Comment by bozhikovstanislav** [comment]
how to start sysadm

**Comment by beanpole135** [comment]
If your users/groups are working properly now, that means the update succeeded, but your system might be one of the ones that is impacted by a bug in the "devmatch" service from upstream TrueOS.

Verify the problem:
   * Run `rc-status` and see if the "devmatch" and "network" services are listed as "stopped"

Fix the problem:
   * Run `sudo edit /etc/rc.conf.d/trident.conf` to open up a text editor on that file.
   * Find the line which looks like this: "rc_network_need=devmatch"
   * Put an "#" at the beginning of that line.
   * Hit the escape key and follow the prompts to save and quit the editor.
   * Run "shutdown -r now" to reboot the system.
   * Everything should properly startup again, including the network service and sysadm.

**Comment by bozhikovstanislav** [comment]
yes thank you - this fix everything :)
now it is working fine

Thank you again

**Comment by bozhikovstanislav** [comment]
I made donation of 5 $
thank you again
