### ISSUE TITLE
Missing terminal emulators and others.

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-build#30]
In the fresh installed Trident-x64-TOS-12-U1-20190731.iso (STABLE) the terminals are missing.
Correctly: 
I tried the install with fish shell and later with the default zsh but for the end the results are same, the terminals are missing from the installed systems. The terminal missing from the "start menu" (where can browsing the apps - bottom left corner) but installed (by the AppCafe) in the context menu (right click on the desktop) the terminal are visible but does not work.

**Comment by beanpole135** [comment]
"fish" and "zsh" are shells, not terminals. QTerminal is the default terminal emulator for Project Trident but it *is* possible for you to de-select it from the list of packages to install from the ISO (which it seems like you did).
If you absolutely must use a terminal but do not have a terminal emulator installed, just switch to a "real" system terminal with Ctl-Alt-F[1-8]. Ctrl-Alt-F9 will return you to the graphical session.

**Comment by ZoltanHegedus** [comment]
I tried to start it from the context menu and  the system tried to start this with the Lumina text editor.

**Comment by ZoltanHegedus** [comment]
Just try the install from DVD and not only from USB key. Today I tried to start  the .iso installer from USB key and from DVD,both in legacy BIOS mode and in UEFI  mode also.

 1. The graphical installer could start in every case.

2. If I started the installer .iso from DVD and from USB key in legacy BIOS mode than:
-the install procedure failed every time with this error messages:
   NEWSFS:/dev/ada1p1 - ZFS vfs.zfs.min_autoashift: 9 ->12
   EXITERROR:Error1:zpool import -f -N
   trident

3. If I started the installer .iso from DVD in UEFI mode than:
- the keyboard layouts were empty in the Graphical Installer and in the installed system also
- for first the target drive selection field was empty (but this can solvable)
- THE APPLICATIONS AND THE FILE SYSTEM SUPPORTS WERE MISSING (Graphical installer). I could finish the install procedure, but some applications (Falcon, QTerminal,Telegram,Trojita etc) were missed from the installed system. This can explain the missing QTerminal emulator problem (earlier I installed only from DVD). At the end of the install procedure some error message readable from the missing packages but these are already missing from the pc-sysinstall.log.

4. If I started the installer .iso from DVD in legacy BIOS mode than: 
- the keyboard layouts were empty in the Graphical Installer
- for first the target drive selection field was empty (but this can solvable)
- THE APPLICATIONS AND THE FILE SYSTEM SUPPORTS WERE MISSING (Graphical installer) and as I wrote in the 2. point sorry the install procedure is failed

5. If I started the installer .iso from USB key in UEFI mode (I missed it at the past with the  Trident-x64-TOS-12-U1-20190731.iso sorry!)  than:
-the target drives were  optional for first, the keyboard layouts were optional but only in the Graphical installer, sorry later these  missing from the installed system and all the applications and file system supports are OK! This method is the best.

Sorry, I was not perfect at the past!
