### ISSUE TITLE
Sysadmin does not start default

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-build#31]
In the fresh installed Trident-x64-TOS-12-U1-20190731.iso (STABLE) the sysadmin does not start default it have to start manually. This can cause problems sometimes (for example the AppCafe can't start).

**Comment by beanpole135** [comment]
I cannot confirm this. I just installed TOS-12-U1 fresh and the AppCafe/sysadm are working perfectly fine with all the default installation options.

**Comment by ZoltanHegedus** [comment]
Confused me the different style (on the system tray) while it searching updates. It searching the updates offline and online also.

**Comment by ZoltanHegedus** [comment]
Sorry, I tried to describe this:

https://www.ixsystems.com/community/threads/update-troubles.78113/post-543478
