### ISSUE TITLE
Missing "video" group

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-build#32]
Maybe is this not a bug, but in the fresh installed Trident-x64-TOS-12-U1-20190731.iso (STABLE) default the "video" group is missing:
https://imgur.com/a/MELhdWr

**Comment by beanpole135** [comment]
You are looking at the "users", not the "groups". The video group is there and all desktop users are automatically added to that group when you login.

**Comment by ZoltanHegedus** [comment]
Oh, sorry Ken you are right!
