### ISSUE TITLE
Prebuild template for Qubes OS

### ISSUE THREAD

**Issue by hegnuzalto** [project-trident/trident-build#34]
There is any chance that team make prebuild template for install in Qubes OS R4?

**Comment by q5sys** [comment]
Thanks for the ticket.  Sadly, this isnt going to be something that the project is able to take on for quite a while.  Ideally this is where someone who is familiar with creating Qubes Templates could contribute. 
However the first step would be for someone to write a Void Template for Qubes.  That would give us something to build on top of.  Until that exists, I don't expect that we'll have the time to focus on this with all the other thing we are currently working on.
