### ISSUE TITLE
Installer Keyboard selection Locale selection

### ISSUE THREAD

**Issue by madewo** [project-trident/trident-build#4]
Sometimes it is possible to select a keyboard-layout, sometimes not for the dropdown-menue is empty. Even if it's possible to select a keybord and/or locale, they are ignored, for the first start it's allways set to 'en' in PCDM, but it is possible to change this successfully in pcdm

**Comment by beanpole135** [comment]
Moved this issue over to the trident-installer repository (with additional information about a possible solution)
