### ISSUE TITLE
Manifest CLI  Option  Does Not Override Default TrueOS Manifest In Makefile

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-build#6]
Providing the trident-master.json manifest via the  command-line option does not override the default TrueOS manifest set in /usr/src_tmp/release/Makefile. This leads to building TrueOS base ISO instead of Trident ISO.

The issue seems to be due to $TRUEOS_MANIFEST variable not exported from the script to Makefile before invoking it.

**Comment by beanpole135** [comment]
Closed by PR #7
